import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {XPRNProvider} from "xprnkit";
import {AppHeader} from "../components/03_organisms/app-header";
import { AppFooter } from "../components/03_organisms/app-footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <XPRNProvider
          config={{
            endpoints: ["https://testnet.rockerone.io"],
            chainId:
              "71ee83bcf52142d61019d95f9cc5427ba6a0d7ff8accd9e2088ae2abeaf3d3dd",
            apiMode: "testnet",
            dAppName: "MetalX Quest",
            requesterAccount: "rockeronebp",
          }}
        >
          <div className="grid grid-rows-[min-content_1fr_min-content] min-h-dvh relative">
            <AppHeader className="sticky top-0 bg-[#0a0a0a] z-20" />
            <div className="md:p-2 flex justify-center items-center p-4 overflow-scroll">
            {children}

            </div>
            <AppFooter />
          </div>
        </XPRNProvider>
      </body>
    </html>
  );
}
