import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { XPRNProvider } from "xprnkit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <XPRNProvider config={{
        chainId: "",
        endpoints: ['https://testnet.rockerone.io'],
        dAppName: "XPR Trust",
        apiMode: "testnet",
        requesterAccount: "xprtrust",
        
      }}
      >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        </body>
        </XPRNProvider>
    </html>
  );
}
